# https://gohugo.io/overview/configuration/

baseurl = "/"
languageCode = "en-us"
title = "Steven Waller › Full-Stack Developer"

# Directory locations
publishDir = "dist"
archetypeDir = "src/markup/archetypes"
contentDir = "src/markup/content"
dataDir = "src/markup/data"
layoutDir = "src/markup/layouts"
themesDir = "src/markup/themes"

# Use TOML for front matter
metaDataFormat = "toml"

# Code syntax highlighting
pygmentsCodeFences = true

# Taxonomies
# Leave empty to remove Category and Tags
[taxonomies]
